In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [46]:
ab=print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [4]:
l = [1,2,5,4,9]

In [5]:
arr =np.array(l)

In [6]:
type(np.array(l))

numpy.ndarray

In [7]:
arr.ndim

1

In [8]:
l = [1,5,4,9,"goutamt"]
arr1= np.array(l)
arr1

array(['1', '5', '4', '9', 'goutamt'], dtype='<U21')

In [9]:
arr1.ndim

1

In [10]:
l=[1,4,5,7]

In [11]:
np.array(l)

array([1, 4, 5, 7])

In [12]:
mat=np.matrix(l)

In [49]:
np.matrix([[1,2],[4,5],[6,7]])

matrix([[1, 2],
        [4, 5],
        [6, 7]])

In [ ]:
np.array([[[1,2],[4,5],[6,7]]])

In [14]:
np.asanyarray([[[1,2],[4,5],[6,7]]])

array([[[1, 2],
        [4, 5],
        [6, 7]]])

In [15]:
mat

matrix([[1, 4, 5, 7]])

In [16]:
np.array(mat)

array([[1, 4, 5, 7]])

In [17]:
t=([1,2,],[5,6])


In [18]:
type(t)

tuple

In [19]:
np.array(t)

array([[1, 2],
       [5, 6]])

In [20]:
a=5

In [21]:
np.array(a)

array(5)

In [22]:

l=[1,5,7,8,9]
arr=np.array(l)
arr

array([1, 5, 7, 8, 9])

In [23]:
a=arr

In [24]:
a

array([1, 5, 7, 8, 9])

In [25]:
arr[0]=1000

In [26]:
arr

array([1000,    5,    7,    8,    9])

In [27]:

a

array([1000,    5,    7,    8,    9])

In [28]:
a[0]=10000

In [29]:
a

array([10000,     5,     7,     8,     9])

In [30]:
arr

array([10000,     5,     7,     8,     9])

In [31]:
d=a.copy()
a[0]=500

In [32]:
d

array([10000,     5,     7,     8,     9])

In [33]:
a

array([500,   5,   7,   8,   9])

In [34]:
d

array([10000,     5,     7,     8,     9])

In [35]:
np.fromfunction(lambda i,j: i==j, shape =(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [36]:
arr1

array(['1', '5', '4', '9', 'goutamt'], dtype='<U21')

In [37]:
arr1.shape

(5,)

In [38]:
arr1.size

5

In [39]:
np.fromfunction(lambda i,j: i*j, shape =(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [40]:
iterable = (i*i for i in range(5))

In [41]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [42]:
np.fromstring('goutam gayatri hemanth 23 55 96', sep =" ")

/tmp/ipykernel_77/3308290265.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('goutam gayatri hemanth 23 55 96', sep =" ")


array([], dtype=float64)

In [43]:
arr.dtype

dtype('int64')

In [44]:
arr.shape

(5,)

In [45]:
arr.size

5

In [46]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [47]:
range(6)

range(0, 6)

In [51]:
list(range(1,3))

[1, 2]

In [49]:
list(np.arange(0.2,5.9,0.1))

[0.2,
 0.30000000000000004,
 0.4000000000000001,
 0.5000000000000001,
 0.6000000000000001,
 0.7000000000000002,
 0.8000000000000003,
 0.9000000000000001,
 1.0000000000000002,
 1.1000000000000003,
 1.2000000000000004,
 1.3000000000000003,
 1.4000000000000004,
 1.5000000000000004,
 1.6000000000000003,
 1.7000000000000004,
 1.8000000000000005,
 1.9000000000000006,
 2.000000000000001,
 2.1000000000000005,
 2.200000000000001,
 2.3000000000000007,
 2.400000000000001,
 2.500000000000001,
 2.600000000000001,
 2.700000000000001,
 2.800000000000001,
 2.9000000000000012,
 3.000000000000001,
 3.100000000000001,
 3.200000000000001,
 3.300000000000001,
 3.4000000000000012,
 3.5000000000000013,
 3.6000000000000014,
 3.7000000000000015,
 3.8000000000000016,
 3.9000000000000012,
 4.000000000000001,
 4.100000000000001,
 4.200000000000002,
 4.300000000000002,
 4.400000000000001,
 4.500000000000002,
 4.600000000000001,
 4.700000000000002,
 4.800000000000002,
 4.900000000000002,
 5.000000000000002,
 5.1000

In [50]:
(np.linspace(1,5,30))

array([1.        , 1.13793103, 1.27586207, 1.4137931 , 1.55172414,
       1.68965517, 1.82758621, 1.96551724, 2.10344828, 2.24137931,
       2.37931034, 2.51724138, 2.65517241, 2.79310345, 2.93103448,
       3.06896552, 3.20689655, 3.34482759, 3.48275862, 3.62068966,
       3.75862069, 3.89655172, 4.03448276, 4.17241379, 4.31034483,
       4.44827586, 4.5862069 , 4.72413793, 4.86206897, 5.        ])

In [51]:
(np.logspace(1,5,10,base=2))

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [52]:
arr1=np.zeros(5)
arr.shape

(5,)

In [53]:
arr2=np.zeros((3,4),int)
arr2.shape

(3, 4)

In [54]:
arr2.ndim

2

In [55]:
arr3=np.zeros((3,3,4),int)
arr3.shape

(3, 3, 4)

In [56]:
arr3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [57]:
arr3.ndim

3

In [58]:
arr=np.ones((3,3,5),int)

In [59]:
arr+5

array([[[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]],

       [[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]],

       [[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]]])

In [60]:
arr*3

array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])

In [61]:
range(7)

range(0, 7)

In [62]:
for i in range (9):
    print(i)

0
1
2
3
4
5
6
7
8


In [63]:
import numpy as np

In [64]:
arr = np.ones((3,4),int)

In [65]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [66]:
arr+7

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [67]:
arr*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [68]:
np.empty((4,5),str)

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [69]:
np.eye(3,dtype=int) 
# to calculate inverse of a matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [70]:
np.empty(5)

array([4.68254821e-310, 0.00000000e+000, 4.68363344e-310, 4.68363347e-310,
       2.37151510e-322])

In [71]:
# optional
import pandas as pd
pd.DataFrame(arr)

0  1  2  3
0  1  1  1  1
1  1  1  1  1
2  1  1  1  1

In [72]:
# extra topic
import random

In [73]:
random.choice((1,2,3,4,5,"goutam"))

'goutam'

In [74]:
random.choice('goutam')

'u'

In [75]:
random.randrange(1,19)

18

In [76]:
random.randrange(1,200)

30

In [77]:
random.random() #a random number is generated between 0 and ,1 will excluded

0.6987963627973511

In [78]:
l=[1,4,5,7,8]
random.shuffle(l)

In [79]:
l

[7, 1, 8, 5, 4]

In [80]:
random.uniform(19,40)

21.24456654278464

In [81]:
np.random.rand(2,4) #to generate random numbers by using numpy

array([[0.35889496, 0.98372994, 0.05773253, 0.51695629],
       [0.00305321, 0.03677925, 0.58958209, 0.01500255]])

In [82]:
np.random.rand(1)

array([0.04702781])

In [83]:
np.random.randn(2,3)

array([[ 1.31268825, -0.21757538, -0.03382945],
       [-0.94577468, -1.93666493,  0.56628899]])

In [84]:
np.random.random_sample() #to gen a random number between 0 and ,1 is excluded

0.9398151561143565

In [85]:
arr=np.random.randint(1,5,(2,3))

In [86]:
np.shape(arr)

(2, 3)

In [87]:
arr.size

6

In [88]:
arr

array([[2, 1, 1],
       [2, 2, 4]])

In [89]:
arr.reshape(6) # reshape will happen if it is the multyple of size

array([2, 1, 1, 2, 2, 4])

In [90]:
arr

array([[2, 1, 1],
       [2, 2, 4]])

In [91]:
arr.reshape(-1, 2) # if i dont know the number of one system in the arr size

array([[2, 1],
       [1, 2],
       [2, 4]])

In [92]:
arr.reshape(3,2).base

array([[2, 1, 1],
       [2, 2, 4]])

In [93]:
arr.size

6

In [94]:
arr.reshape(3,1,2)

array([[[2, 1]],

       [[1, 2]],

       [[2, 4]]])

In [95]:
arr.reshape(2,1,3,1)

array([[[[2],
         [1],
         [1]]],


       [[[2],
         [2],
         [4]]]])

In [96]:
list=[1,2,3,4]
arr=np.array(list)

In [97]:
arr.ndim

1

In [98]:
arr2=np.array([[2,3],[4,5]])

In [99]:
arr2.ndim

2

In [100]:
arr2=np.zeros((3,4),int)

In [101]:
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [102]:
arr2.ndim

2

In [103]:
arr3 = np.zeros((1,3,4),int) # 3 rows,4 coloumns,1 extra dimension

In [104]:
arr3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [105]:
arr3.ndim

3

In [106]:
arr4 = np.zeros((1,1,3,4),int)

In [107]:
arr4

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]])

In [108]:
arr4.ndim

4

In [109]:
arr2=np.zeros((2,3,4),int)

In [110]:
arr2

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [111]:
arr1=np.random.randint(1,10,(5,6))

In [112]:
arr1

array([[9, 3, 5, 8, 1, 6],
       [2, 6, 9, 9, 9, 8],
       [4, 6, 5, 6, 5, 4],
       [1, 5, 6, 7, 2, 3],
       [6, 4, 7, 3, 6, 7]])

In [113]:
arr1 > 4

array([[ True, False,  True,  True, False,  True],
       [False,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True, False],
       [False,  True,  True,  True, False, False],
       [ True, False,  True, False,  True,  True]])

In [114]:
arr1[arr1 > 4]

array([9, 5, 8, 6, 6, 9, 9, 9, 8, 6, 5, 6, 5, 5, 6, 7, 6, 7, 6, 7])

In [115]:
arr1

array([[9, 3, 5, 8, 1, 6],
       [2, 6, 9, 9, 9, 8],
       [4, 6, 5, 6, 5, 4],
       [1, 5, 6, 7, 2, 3],
       [6, 4, 7, 3, 6, 7]])

In [116]:
arr1[0]

array([9, 3, 5, 8, 1, 6])

In [117]:
arr1[0][4]

1

In [118]:
import numpy as np

In [119]:
a= np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [120]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [121]:
b= np.array([16,-8,0])

In [122]:
b

array([16, -8,  0])

In [123]:
np.linalg.solve(a,b)

array([0.90162081, 2.89483603, 1.88465888])

In [124]:
arr= np.array([[2,3],[4,5]])

In [125]:
arr

array([[2, 3],
       [4, 5]])

In [126]:
5*2 - 3*4

-2

In [127]:
np.linalg.det(arr )

-2.0

In [128]:
np.linalg.inv(arr )

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [130]:
np.fromfunction( lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [137]:
np.fromfunction( lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [131]:
arr1

array([[9, 3, 5, 8, 1, 6],
       [2, 6, 9, 9, 9, 8],
       [4, 6, 5, 6, 5, 4],
       [1, 5, 6, 7, 2, 3],
       [6, 4, 7, 3, 6, 7]])

In [133]:
arr1.shape

(5, 6)

In [134]:
arr

array([[2, 3],
       [4, 5]])

In [135]:
arr.shape

(2, 2)

In [136]:
arr.size

4

In [138]:
iterable=(i*i for i in range(5))

In [140]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [146]:
np.fromstring("23  45  78",sep = "  ")

array([23., 45., 78.])

In [5]:
import numpy as np
arr = np.ones((3,5), int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
arr+5

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [9]:
arr*6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [20]:
np.empty((2,2),int)

array([[72340172821233665, 72340172838076673],
       [72340172838076673, 72340172838076673]])

In [26]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [28]:
# optional

import pandas as pd
pd.DataFrame(arr)

0  1  2  3  4
0  1  1  1  1  1
1  1  1  1  1  1
2  1  1  1  1  1

In [29]:
# extra topic
import random

In [34]:
random.choice((1,2,3,4,5))

5

In [37]:
random.randrange(1,50)

3

In [38]:
random.random() 

0.5010763166543517

In [45]:
lis = [8,7,5,6,9]
random.shuffle(lis)

In [46]:
lis

[8, 7, 6, 5, 9]

In [55]:
random.uniform(0,196)

95.33256233390765

In [56]:
np.random.rand(2,3)

array([[0.02774051, 0.24631669, 0.90514154],
       [0.19028138, 0.90080798, 0.98657925]])

In [57]:
np.random.rand(1)

array([0.10404207])

In [2]:
import numpy as np

In [3]:
np.random.random_sample()

0.44363946157260337

In [4]:
np.random.randint(1,5,(3,4))

array([[1, 1, 2, 4],
       [1, 1, 2, 2],
       [3, 3, 2, 4]])

In [5]:
arr =np.random.randint(1,5,(3,4))

In [6]:
arr.ndim

2

In [7]:
arr.size

12

In [8]:
arr.shape

(3, 4)

In [9]:
arr.reshape(2,6)

array([[4, 3, 2, 2, 3, 2],
       [3, 3, 1, 1, 4, 4]])

In [10]:
arr.reshape(4,3)

array([[4, 3, 2],
       [2, 3, 2],
       [3, 3, 1],
       [1, 4, 4]])

In [11]:
arr.reshape(12,)

array([4, 3, 2, 2, 3, 2, 3, 3, 1, 1, 4, 4])

In [12]:
arr.reshape(12,1)

array([[4],
       [3],
       [2],
       [2],
       [3],
       [2],
       [3],
       [3],
       [1],
       [1],
       [4],
       [4]])

In [13]:
arr.reshape(4,-1) # if you don't know the number of columns

array([[4, 3, 2],
       [2, 3, 2],
       [3, 3, 1],
       [1, 4, 4]])

we need to know atleast one count of the matrix to reshape it 

In [14]:
arr.reshape(12,1).base

array([[4, 3, 2, 2],
       [3, 2, 3, 3],
       [1, 1, 4, 4]])

In [17]:
arr.reshape(3,2,2)

array([[[4, 3],
        [2, 2]],

       [[3, 2],
        [3, 3]],

       [[1, 1],
        [4, 4]]])

In [19]:
arr.reshape(1,1,1,2,2,3)

array([[[[[[4, 3, 2],
           [2, 3, 2]],

          [[3, 3, 1],
           [1, 4, 4]]]]]])

In [20]:
list = [1,2,6,5]

In [23]:
arr=np.array(list)

In [24]:
arr.ndim

1

In [26]:
arr2 = np.array([[2,3],[4,5]])

In [27]:
arr2.ndim

2

In [28]:
arr2= np.zeros((4,5))
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
arr2.ndim

2

In [31]:
arr3=np.zeros((1,2,3))
arr3

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
arr3.ndim

3

In [34]:
arr3.shape

(1, 2, 3)

In [38]:
arr4 = np.ones((1,1,4,2),int)

In [39]:
arr4

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]])

In [40]:
arr4.ndim

4

In [47]:
arr2= np.zeros((2,4,5))
arr2

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [44]:
arr2.ndim

3

In [48]:
arr2.shape

(2, 4, 5)

In [52]:
arr1=np.random.randint(1,10,(5,6))

In [53]:
arr1>5

array([[False,  True,  True, False, False,  True],
       [ True, False, False,  True,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [ True, False, False, False, False,  True],
       [False,  True,  True, False, False,  True]])

In [55]:
arr1[arr1>5]

array([7, 9, 6, 8, 7, 9, 9, 9, 7, 7, 7, 7, 7, 8, 9, 6, 9])

In [56]:
arr1[arr1<5]

array([2, 1, 2, 3, 2, 4, 3, 2, 1, 4])

In [57]:
arr

array([1, 2, 6, 5])

In [61]:
arr[3]

5

In [62]:
arr1

array([[2, 7, 9, 1, 2, 6],
       [8, 3, 2, 7, 9, 9],
       [9, 5, 7, 7, 7, 7],
       [7, 4, 5, 3, 2, 8],
       [5, 9, 6, 1, 4, 9]])

In [77]:
arr1[0][5]

6

In [72]:
arr1[0,[0,2]]

array([2, 9])

In [78]:
arr1[2:6,(0,3)] #slicing of matrix 

array([[9, 7],
       [7, 3],
       [5, 1]])

In [79]:
arr1[[2,4]]

array([[9, 5, 7, 7, 7, 7],
       [5, 9, 6, 1, 4, 9]])

In [80]:
arr1[2:4]

array([[9, 5, 7, 7, 7, 7],
       [7, 4, 5, 3, 2, 8]])

In [85]:
arr1[2:5,[1,3]]

array([[5, 7],
       [4, 3],
       [9, 1]])

In [82]:
arr1

array([[2, 7, 9, 1, 2, 6],
       [8, 3, 2, 7, 9, 9],
       [9, 5, 7, 7, 7, 7],
       [7, 4, 5, 3, 2, 8],
       [5, 9, 6, 1, 4, 9]])

In [89]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [100]:
arr1

array([[1, 2, 1],
       [1, 1, 1],
       [2, 1, 1]])

In [101]:
arr2

array([[1, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [102]:
arr1+arr2

array([[2, 4, 3],
       [3, 3, 3],
       [4, 3, 3]])

In [103]:
arr1 * arr2

array([[1, 4, 2],
       [2, 2, 2],
       [4, 2, 2]])

In [93]:
arr1-arr2

array([[ 0,  0, -1],
       [-1, -1, -1],
       [ 0, -1, -1]])

In [104]:
arr1@arr2

array([[7, 8, 8],
       [5, 6, 6],
       [6, 8, 8]])

In [106]:
arr1/arr2

array([[1. , 1. , 0.5],
       [0.5, 0.5, 0.5],
       [1. , 0.5, 0.5]])

In [107]:
arr1/0

/tmp/ipykernel_98/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

# Broad casting

In [110]:
arr=np.zeros((3,4))

In [111]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [122]:
a=np.array([1,2,3,4])

In [123]:
a

array([1, 2, 3, 4])

In [124]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [131]:
a=np.array([[1,2,3]])

In [132]:
a

array([[1, 2, 3]])

In [133]:
a.T

array([[1],
       [2],
       [3]])

In [134]:
arr+a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [137]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ],
       [1.41421356, 1.        , 1.        ]])

In [138]:
np.amin(arr1)

1

In [139]:
np.log10(arr1)

array([[0.     , 0.30103, 0.     ],
       [0.     , 0.     , 0.     ],
       [0.30103, 0.     , 0.     ]])

In [140]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183]])

In [141]:
arr1

array([[1, 2, 1],
       [1, 1, 1],
       [2, 1, 1]])

In [142]:
np.min(arr1)

1

In [143]:
np.max(arr1)

2

In [144]:
arr1

array([[1, 2, 1],
       [1, 1, 1],
       [2, 1, 1]])

In [145]:
arr1.T

array([[1, 1, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [146]:
arr1.flatten() # Reduce dimension to 1d

array([1, 2, 1, 1, 1, 1, 2, 1, 1])

# Expand_dims

In [147]:
arr = np.array([[1,2,3],[4,5,6]])

In [148]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
np.sum(arr)

21

In [151]:
np.sum(arr,axis=0)

array([5, 7, 9])

In [152]:
np.sum(arr,axis=1)

array([ 6, 15])

In [154]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [155]:
arr.ndim

1

In [157]:
np.expand_dims(arr,axis=0)

array([[1, 2, 3, 4]])

In [158]:
arr1=np.expand_dims(arr,axis=0)

In [160]:
 arr1.ndim

2

In [162]:
arr2=np.expand_dims(arr1,axis=0)
arr2

array([[[1, 2, 3, 4]]])

In [163]:
arr2.ndim

3

In [164]:
arr

array([1, 2, 3, 4])

In [165]:
arr1=np.expand_dims(arr,axis=1)

In [166]:
arr1

array([[1],
       [2],
       [3],
       [4]])

In [168]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [169]:
arr1=np.expand_dims(arr,axis=0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [170]:
arr1=np.expand_dims(arr,axis=1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [13]:
import numpy as np
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [14]:
data.ndim

2

In [15]:
np.squeeze(data)

array([1, 2, 3])

In [16]:
# repeat
data

array([[1],
       [2],
       [3]])

In [17]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [18]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [19]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [29]:
a.reshape(4).base

array([[1, 2],
       [3, 4]])

In [32]:
np.repeat(a,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [33]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [34]:
data

array([[1],
       [2],
       [3]])

In [35]:
data

array([[1],
       [2],
       [3]])

In [41]:
np.roll(data,210)

array([[1],
       [2],
       [3]])

In [43]:
np.diag(np.array([1,2,3,4,5,6]))

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [45]:
np.roll(data,-3)

array([[1],
       [2],
       [3]])

In [53]:
a=np.array([[[1,2],[3,4]]])

In [54]:
a.ndim

3

In [56]:
np.roll(a,2)

array([[[3, 4],
        [1, 2]]])

In [58]:
np.roll(a,2,axis=0)

array([[[1, 2],
        [3, 4]]])

# Binary operation on array 

In [59]:
arr1=np.random.randint(1,10,(3,4))

In [76]:
arr2=np.random.randint(1,10,(3,4))

In [77]:
arr1


array([[7, 3, 6, 6],
       [5, 6, 7, 9],
       [5, 7, 1, 9]])

In [78]:
arr2

array([[6, 8, 8, 4],
       [1, 3, 8, 2],
       [3, 3, 4, 6]])

In [79]:
arr1+arr2

array([[13, 11, 14, 10],
       [ 6,  9, 15, 11],
       [ 8, 10,  5, 15]])

In [80]:
arr1*arr2

array([[42, 24, 48, 24],
       [ 5, 18, 56, 18],
       [15, 21,  4, 54]])

In [81]:
arr1**arr2

array([[ 117649,    6561, 1679616,    1296],
       [      5,     216, 5764801,      81],
       [    125,     343,       1,  531441]])

In [75]:
arr2 @ arr1

array([[133, 117, 116, 180],
       [ 79,  60,  66,  96],
       [108, 117,  82, 168],
       [ 65,  55,  48,  84]])

In [82]:
~arr1

array([[ -8,  -4,  -7,  -7],
       [ -6,  -7,  -8, -10],
       [ -6,  -8,  -2, -10]])

In [83]:
arr1

array([[7, 3, 6, 6],
       [5, 6, 7, 9],
       [5, 7, 1, 9]])

# Numpy string function

In [84]:
arr = np.array(['pw','skills'])

In [85]:
arr

array(['pw', 'skills'], dtype='<U6')

In [86]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [88]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [89]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

# Mathmatical operation

In [90]:
arr1

array([[7, 3, 6, 6],
       [5, 6, 7, 9],
       [5, 7, 1, 9]])

In [91]:
np.sin(arr1)

array([[ 0.6569866 ,  0.14112001, -0.2794155 , -0.2794155 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.41211849],
       [-0.95892427,  0.6569866 ,  0.84147098,  0.41211849]])

In [92]:
np.cos(arr1)

array([[ 0.75390225, -0.9899925 ,  0.96017029,  0.96017029],
       [ 0.28366219,  0.96017029,  0.75390225, -0.91113026],
       [ 0.28366219,  0.75390225,  0.54030231, -0.91113026]])

In [93]:
np.log10(arr1)

array([[0.84509804, 0.47712125, 0.77815125, 0.77815125],
       [0.69897   , 0.77815125, 0.84509804, 0.95424251],
       [0.69897   , 0.84509804, 0.        , 0.95424251]])

In [94]:
np.exp(arr1)

array([[1.09663316e+03, 2.00855369e+01, 4.03428793e+02, 4.03428793e+02],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 8.10308393e+03],
       [1.48413159e+02, 1.09663316e+03, 2.71828183e+00, 8.10308393e+03]])

In [96]:
np.power(arr1,3)

array([[343,  27, 216, 216],
       [125, 216, 343, 729],
       [125, 343,   1, 729]])

In [97]:
np.max(arr1)

9

In [98]:
np.min(arr1)

1

In [99]:
np.std(arr1)

2.1778557242286634

In [100]:
np.var(arr1)

4.743055555555556

In [101]:
np.subtract(arr1,arr2)

array([[ 1, -5, -2,  2],
       [ 4,  3, -1,  7],
       [ 2,  4, -3,  3]])

In [102]:
np.multiply(arr1,arr2)

array([[42, 24, 48, 24],
       [ 5, 18, 56, 18],
       [15, 21,  4, 54]])

In [103]:
np.power(arr1,arr2)

array([[ 117649,    6561, 1679616,    1296],
       [      5,     216, 5764801,      81],
       [    125,     343,       1,  531441]])

In [104]:
np.mod(arr1,arr2) # return element wise remainder

array([[1, 3, 6, 2],
       [0, 0, 7, 1],
       [2, 1, 1, 3]])

In [105]:
np.sqrt(arr1)

array([[2.64575131, 1.73205081, 2.44948974, 2.44948974],
       [2.23606798, 2.44948974, 2.64575131, 3.        ],
       [2.23606798, 2.64575131, 1.        , 3.        ]])

# Sort & Search in array

In [106]:
arr = np.array([5,6,7,3])

In [107]:
arr

array([5, 6, 7, 3])

In [113]:
np.sort(arr)

array([3, 5, 6, 7])

In [121]:
np.searchsorted(arr,100)

4

In [122]:
arr1 = np.array([0,1,2,3,4,0])
np.count_nonzero(arr1)

4

In [126]:
np.where(arr1>3)

(array([4]),)

In [125]:
np.extract(arr1 > 3,arr1)

array([4])

In [127]:
arr1

array([0, 1, 2, 3, 4, 0])

In [128]:
arr1.byteswap()

array([                 0,  72057594037927936, 144115188075855872,
       216172782113783808, 288230376151711744,                  0])

# Matrix == 2d array

In [1]:
import numpy.matlib as nm

In [5]:
import numpy as np

In [6]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [7]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [9]:
arr1 = np.array([[2,3],[4,5]])
arr2= np.array([[1,3],[4,5]])

In [10]:
arr1

array([[2, 3],
       [4, 5]])

In [11]:
arr2

array([[1, 3],
       [4, 5]])

In [152]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [12]:
a= np.array([[7,5,-3],[3,-5,2],[5,3,-7]])

In [13]:
a

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [14]:
b=np.array([16,-8,0])

In [15]:
b

array([16, -8,  0])

In [16]:
np.linalg.solve(a,b)

array([1., 3., 2.])

In [17]:
arr1

array([[2, 3],
       [4, 5]])

In [19]:
np.linalg.det(arr1)

-2.0

In [20]:
arr1 = np.random.randint(1,3,(3,3))

In [21]:
arr1

array([[2, 1, 1],
       [1, 2, 2],
       [2, 1, 2]])

In [22]:
np.linalg.det(arr1)

2.9999999999999996